namespace: "alcnsahin"
name: "soap-request"
version: "1.0.0"
readme: "README.md"
description: "Simple SOAP client. Also supports rest calls"
authors:
    - "Alican Sahin <alcnsahin@gmail.com>"
dependencies:
license:
    - "MIT"
tags:
    - soap
    - rest
    - api
    - web service
repository: "https://github.com/alcnsahin/ansible-soap-request"
documentation: "https://github.com/alcnsahin/ansible-soap-request"
homepage: "https://github.com/alcnsahin/ansible-soap-request"
issues: "https://github.com/alcnsahin/ansible-soap-request/issues"